name: Build Latex Document

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_print:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git repository
        uses: actions/checkout@v4
      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
      - run: perl get-referenced-rfcs > all-rfcs.bib
      - name: Compile Latex Document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: BGP_for_networks_who_peer.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: BGP_for_networks_who_peer.pdf
