name: Build Latex Document

on:
  push:
    tags:
      - v2024-**
  workflow_dispatch:
  

permissions:
  contents: write

jobs:
  build_print:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Git repository
        uses: actions/checkout@v4
      - name: Setup Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          install-modules: "LWP::UserAgent"
      - run: cat *.tex tex/*.tex | perl get-referenced-rfcs > all-rfcs.bib
      - name: Upload Bibtex file
        uses: actions/upload-artifact@v4
        with:
          name: all-rfcs
          path: all-rfcs.bib

#      - name: Compile Latex Document
#        uses: xu-cheng/latex-action@v3
#        with:
#          root_file: BGP_for_networks_who_peer.tex
#      - name: Upload PDF file
#        uses: actions/upload-artifact@v4
#        with:
#          name: BGP_for_networks_who_peer
#          path: BGP_for_networks_who_peer.pdf
#      - name: Release
#        uses: softprops/action-gh-release@v1
#        with:
#          files: BGP_for_networks_who_peer.pdf
